import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../../prisma/prisma.service';
import { UserType, UserRole, JobCategory, JobStatus } from '@prisma/client';
import * as bcrypt from 'bcrypt';

// Import UrgencyLevel since it's not generated by default in Prisma Client
enum UrgencyLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}

@Injectable()
export class DatabaseSeeder {
  constructor(private readonly prisma: PrismaService) {}

  async seed(): Promise<void> {
    await this.seedUsers();
    await this.seedJobs();
    console.log('Database seeded successfully!');
  }

  private async seedUsers(): Promise<void> {
    const users = [
      {
        email: 'client@example.com',
        passwordHash: await bcrypt.hash('password123', 10),
        fullName: 'John Client',
        city: 'Bucharest',
        county: 'Bucharest',
        userType: UserType.INDIVIDUAL,
        role: UserRole.CLIENT,
        isVerified: true,
        specialties: ['general'] as string[],
      },
      {
        email: 'craftsman@example.com',
        passwordHash: await bcrypt.hash('password123', 10),
        fullName: 'Mike Craftsman',
        city: 'Bucharest',
        county: 'Bucharest',
        userType: UserType.INDIVIDUAL,
        role: UserRole.CRAFTSMAN,
        isVerified: true,
        bio: 'Experienced electrician with 10+ years in residential and commercial work.',
        averageRating: 4.8,
        totalReviews: 25,
        specialties: ['electrik'] as string[],
      },
      {
        email: 'admin@mesteri.ro',
        passwordHash: await bcrypt.hash('admin123', 10),
        fullName: 'Admin Mesteri',
        city: 'Bucharest',
        county: 'Bucharest',
        userType: UserType.INDIVIDUAL,
        role: UserRole.CLIENT,
        isVerified: true,
        specialties: ['admin'] as string[],
      },
    ];

    for (const userData of users) {
      const existingUser = await this.prisma.user.findUnique({
        where: { email: userData.email },
      });

      if (!existingUser) {
        await this.prisma.user.create({
          data: userData,
        });
        console.log(`Created user: ${userData.email}`);
      }
    }
  }

  private async seedJobs(): Promise<void> {
    const client = await this.prisma.user.findUnique({
      where: { email: 'client@example.com' },
    });

    if (!client) return;

    const jobs = [
      {
        title: 'Instalatii Electrice in Bucatarie',
        description:
          'Instalare prize si corpuri iluminat in renovare bucatarie moderna. Spatiul aproximativ 15mp necesita 4 prize noi, iluminat sub-taval, si un dispozitiv de protectie.',
        category: JobCategory.ELECTRIK,
        budgetMin: 1500.0,
        budgetMax: 2500.0,
        city: 'Bucuresti',
        location: 'Sector 1',
        status: JobStatus.ACTIVE,
        clientId: client.id,
      },
      {
        title: 'Reparatii Instalatii Sanitare',
        description:
          'Reparatie robinet picurator si inlocuire duca. Verificare pentru coroziune teava sub chiuveta. Materiale furnizate de client.',
        category: JobCategory.INSTALATII_SANITARE,
        budgetMin: 200.0,
        budgetMax: 400.0,
        city: 'Bucuresti',
        location: 'Sector 2',
        status: JobStatus.ACTIVE,
        clientId: client.id,
      },
      {
        title: 'Constructie Terasa Lemn',
        description:
          'Constructie terasa 20mp a gradina. Necesita lemn tratat la presiune, fundament solid, si balustrade de siguranta. Trebuie sa respecte codurile locale de constructii.',
        category: JobCategory.CONSTRUCTII,
        budgetMin: 3000.0,
        budgetMax: 5000.0,
        city: 'Otopeni',
        location: 'Otopeni',
        status: JobStatus.ACTIVE,
        clientId: client.id,
      },
    ];

    for (const jobData of jobs) {
      const existingJob = await this.prisma.job.findFirst({
        where: {
          title: jobData.title,
          clientId: jobData.clientId,
        },
      });

      if (!existingJob) {
        await this.prisma.job.create({
          data: jobData,
        });
        console.log(`Created job: ${jobData.title}`);
      }
    }
  }
}
